version: "3.7"

services:
  nest-app:
    image: iceman951/nestjs-app-for-jenkins:${APPVERSION}
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DATABASE: postgres-db
      POSTGRES_PORT: 5432
    ports:
      - 3000:3000w

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    volumes:
      - .:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres-db

# volumes:
#   events-data:
