version: "3.7"

services:
  nest-app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DATABASE: postgres-db
      POSTGRES_PORT: 5432
    ports:
    - 3000:3000

  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres-db