apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-nodeport-service
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30300 # กำหนดหมายเลข NodePort (30000-32767)
  selector:
    app: postgres-deployment
  type: NodePort # เพิ่มเติมในส่วนของประเภทให้เป็น NodePort