apiVersion: v1
kind: PersistentVolume
metadata:
  name: nestjs-pv
  namespace: nestjs
spec:
  storageClassName: nestjs-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/k8s/data"

