apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nestjs-pv-claim
  namespace: nestjs
spec:
  storageClassName: nestjs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
